language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: ckkAqxPyuQsX3dvGDU64wS7Uh2kCA6t4gFm/jHEa7qcBwOMb1CbxnhWtyi9smH7YR927F6vzV8wQhbDS9wOydIcOfG1r26fmBufUkAQzKxmOonyrvTMtTV/DhpxyMtxDyI/hn7u5iKu7U5b9rF14GrDNYTbXDMzjQYgPX24Czlnt4NazCB8kBcL/jAleL1LcBv6/ZR0YnY7N0NgaLMMCSj20pmqebEZXhUssLCbq1izRid2nh40zzC5YDcRy6LerGJ/AAZQFFjj0ojq6VABxOGkMUUuDUMMeewOi/rKdfLeGSe1y3CxYXHji3MVvWqD7kDp+mLbUuIASG6CFk3E18MxPUgCFehgprNV8S6KYfALC6SJ/esQolP/vgx5CPBQsGfK+LMlLj12Y7dqMQuG9e44kzooWUf+Y49HmxLT3S70GVgjI9B/hcS3d2l5we01tlujQ851tCRvO/V0PgtK59wKcVNQhFODy/8A8bgymqt/JyYfm5m3Q8ZN5alQsj6/wqv2SLeHh3cHRo7wLItXLytuQAI7vtG6YokKzZYosFVyABAZmxE1pHPkJUtdC9k1hbyN6Z9f6fIJVgJSM6aECgM/0iuHL39oPmAVlby7ZPjJijihJSBYPr/4EhDOzJatt63/8/XCKRbp7o3R3Hruw8o8p3WmQ5+ChihVAV+vneqk=
