language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: lwtcAdTXkjAmb5TW4/y42eumISbevDT46j4d5DZdJTKOzqjsWa33rKbyVcHw4pi4gpqsZLy9PEDta8NGBRvcbcXeJHjZEVdohDQwB9pL25FKuL1El6xtvPIwQsyybEtZEHzeXvgLfedyAE1zsDa3TXAZj7hN4TZZWgkQZuYGkDTyTpZcQCY/MXC3TX0VONx8EyeSv1fBxO6/kEBpW2wiMAgMzOGAZY3wkYDsXdK+clgvSCTqnGo0i4A+f/sptT0i+3csPAm3SfzU1gh8BiHxm4RvGVVqrOQFK+gPIODDfI827cvmk4sHCYed7+WsJnKT7iYE5kZ885Ep9rOcGj0MKA80SxOvxtwdfKwKxnelr/SeAgJOZ+dM810MknID1E2HxgxMfHpQPOtZcA+d+aLMVAlDMIKBcRVN/MR1oG670sgOH3AvHquP2ByzMLAsQe55eFMoSSvBhaIdYFMVfKz7BvHvVy/SndfycQ0sV/r/OvGD2IRk80koJd8qCo3aZa1x/B56yCyx0E6ibH9e0FeG3ZhUKRTcjXenykadRmPzqxj7EslJg3d5lkmfZrvV3UEiXVGXoP9wk5RhKZ7CCqOMSRghsW2q48dh+xhRPNzflI1X/xDfYNVUQffmzsTdNiPtLZ2DOwLjinT0DfYhPhB9VAvQLKspZBGSznLevOcwuQ4=
