language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: VsoomIt6D+2v4VZZz7eSqY9sUu+En9GMyoJd5llN9jfTbcPdonQgnFjygictR853IHJ2EgUon0p88nlVs1nWSU8dtiNmebyMiVtGH9LiWbbyej0vWclym0gwuYe+iaaz8j70kjAlFQKts17XPdQu/L1le3OOlIaNcZHV1R1PFptOHrWD3GgAJLKmuqTzlzRxw7DhMV50/t9LtBJ5sr94pPzVOjEsPx+5lRBUVkNSFnMGezDvFdX3uHY+Tdac47Sr3z0+kKddlwEGPF1q1hbQ1AJZYnk8vvZAoUfHMllQCS3jbm7Gc7Gh1dAtLWDVrx2F957d46kYedC16e76p1xEq6NwV6veDLIwsHFRuafZvZzTkRhKZs2ZFarA1C6fFDPhlewgWQVHHo9IEIdpGreRZCG6RwXmbCx7nb+tIjVzEPdBA0ss2hTTr7vawHrhk4epu5qcK6MsfGrAMIBxMh33gn2d/OLQ4ajaApn7TWJJ3sUkKE5pLDWh5eiQqjOa2zpKOP9NLaS0iDkRwj9T2CvR+keyrG2U321TIWQhKcSqXRcGAwMkgyD3RGNsWm+jrw7o81LQBMta6cGe6762v/onqPbiaPmTxMzhSdMT9016JGRIpEkBVup9pmKbPpV/lFMx9vtEf0Pzwe85pDk8Q4MS2lInr5m8aSQVmP3fzPrwqII=
  app: d3js-react-examples
  on:
    repo: burakince/d3js-react-examples
