language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI
- npm run build
deploy:
  api_key:
    secure: eWcM4reKfHj6KrORpRfmSZqdBPIC8zo+71+RZRi/WW/bx984a5tbDlF6PShBzNOPBh0vSlD5dt9UTsJj0TsmmotBuskgiGofxgxsF13CNXZjImkqjvj6O6dsQeVLz+mHOJ7Jm2Gwgx8cOIH6DaHGGyZePX8s4BQZWqktS1AeGqDhk44EMw+Qcd7hIFfyqYAR0LCLH3VBIgHS57RW57wyeAw3j5c3KkWtUopCBDsqG+mcdnvrI2knLKGrEKLqGsiNoGSfxzP5GX1wSdQ7vZLfN7K72Voq3kb9L25qBub5QQmsF06CaMkZLQ2Q4cxWZ1jEUz33UEqc53JzIuiSzmlqItHBJBYimWm1uirbLEWr8h6NstmtJzXqrYTfFbf5XqDmxDNmNpG4u9GxL6+gQ81FqsZ9Jz553ItpBZ2M2GFvF3tKWt4RqAWyZ87QVZo7NmScXK0/kAU+HHzL/10YDwEOdlC/pJYWiN5y1g2lwSyGR7g1i2lght3qjVxNCqTntERd+l7RVWBT2GIBkIgPOFjDmP9ZQjJ4eXxVdBnVqhMQ+w2Fhc179OjKnAp6WVB921FaJKu+XwUqWS22X3zTsQamAfsSzHEdACFGfW+M2c6EwJpBNKZxKVYjn5rehWGktj4W96Mo5hpDR7WiU/c/B+COjtaz6Tv9TVeUw5xpCL+R81Q=
